import type {
  AccessReference,
  LibraryItem,
  Project,
  RdaContentItem,
  Task,
} from "@/lib/types"

export const initialProjects: Project[] = [
  {
    id: "diego-aranda-web",
    name: "Diego Aranda Web",
    client: "Cliente",
    status: "Activo",
    priority: "Alta",
    nextAction: "Maquetar sección de servicios",
    progress: 65,
    links: [
      { label: "Repositorio", href: "#" },
      { label: "Figma", href: "#" },
      { label: "Deploy", href: "#" },
    ],
  },
  {
    id: "medalleros-web",
    name: "Medalleros Web",
    client: "Cliente",
    status: "Activo",
    priority: "Alta",
    nextAction: "Integrar catálogo de productos",
    progress: 40,
    links: [
      { label: "Repositorio", href: "#" },
      { label: "Brief", href: "#" },
    ],
  },
  {
    id: "rey-abasto-web",
    name: "Rey del Abasto Web",
    client: "Rey del Abasto",
    status: "En pausa",
    priority: "Media",
    nextAction: "Esperando fotos de producto",
    progress: 25,
    links: [
      { label: "Figma", href: "#" },
      { label: "Notas", href: "#" },
    ],
  },
  {
    id: "rey-abasto-marketing",
    name: "Rey del Abasto Marketing",
    client: "Rey del Abasto",
    status: "Activo",
    priority: "Alta",
    nextAction: "Cerrar calendario semanal",
    progress: 70,
    links: [
      { label: "Calendario", href: "#" },
      { label: "Drive", href: "#" },
    ],
  },
  {
    id: "home-finance-os",
    name: "Home Finance OS",
    client: "Personal",
    status: "Planificación",
    priority: "Media",
    nextAction: "Definir estructura de presupuesto",
    progress: 15,
    links: [{ label: "Notion", href: "#" }],
  },
  {
    id: "personal-admin",
    name: "Personal / Admin",
    client: "Personal",
    status: "Activo",
    priority: "Baja",
    nextAction: "Revisar facturación del mes",
    progress: 50,
    links: [{ label: "Documentos", href: "#" }],
  },
]

export const initialTasks: Task[] = [
  {
    id: "t1",
    title: "Maquetar sección de servicios de Diego Aranda",
    status: "En curso",
    priority: "Alta",
    projectId: "diego-aranda-web",
    due: "Hoy",
    source: "Manual",
  },
  {
    id: "t2",
    title: "Cerrar calendario de contenido Rey del Abasto",
    status: "En curso",
    priority: "Alta",
    projectId: "rey-abasto-marketing",
    due: "Hoy",
    source: "ClickUp",
  },
  {
    id: "t3",
    title: "Responder correo de Medalleros sobre catálogo",
    status: "Pendiente",
    priority: "Alta",
    projectId: "medalleros-web",
    due: "Hoy",
    source: "Manual",
  },
  {
    id: "t4",
    title: "Integrar catálogo de productos Medalleros",
    status: "Pendiente",
    priority: "Media",
    projectId: "medalleros-web",
    due: "Mañana",
    source: "ClickUp",
  },
  {
    id: "t5",
    title: "Revisar copy de home Diego Aranda",
    status: "En revisión",
    priority: "Media",
    projectId: "diego-aranda-web",
    due: "Mañana",
    source: "Manual",
  },
  {
    id: "t6",
    title: "Esperando fotos de producto Rey del Abasto",
    status: "Bloqueado",
    priority: "Media",
    projectId: "rey-abasto-web",
    due: "Sin fecha",
    source: "Manual",
  },
  {
    id: "t7",
    title: "Definir estructura de presupuesto Home Finance",
    status: "Pendiente",
    priority: "Media",
    projectId: "home-finance-os",
    due: "Esta semana",
    source: "Manual",
  },
  {
    id: "t8",
    title: "Revisar facturación del mes",
    status: "Pendiente",
    priority: "Baja",
    projectId: "personal-admin",
    due: "Esta semana",
    source: "ClickUp",
  },
  {
    id: "t9",
    title: "Deploy final landing Diego Aranda",
    status: "Terminado",
    priority: "Alta",
    projectId: "diego-aranda-web",
    due: "Ayer",
    source: "Manual",
  },
  {
    id: "t10",
    title: "Aprobar diseño de banner semanal",
    status: "En revisión",
    priority: "Media",
    projectId: "rey-abasto-marketing",
    due: "Mañana",
    source: "ClickUp",
  },
]

export const initialInboxItems = [
  {
    id: "i1",
    content: "Preguntar a Diego por acceso al hosting",
    createdAt: "Hace 2 h",
    suggestedProject: "diego-aranda-web",
  },
  {
    id: "i2",
    content: "Idea: reel mostrando el proceso de empaque del abasto",
    createdAt: "Hace 5 h",
    suggestedProject: "rey-abasto-marketing",
  },
  {
    id: "i3",
    content: "Cotizar plugin de facturación para Medalleros",
    createdAt: "Ayer",
    suggestedProject: "medalleros-web",
  },
  {
    id: "i4",
    content: "Configurar recordatorio de pagos mensuales",
    createdAt: "Ayer",
    suggestedProject: "home-finance-os",
  },
]

export const initialRdaContentItems: RdaContentItem[] = [
  {
    id: "c1",
    product: "Aceite de oliva premium",
    format: "Reel",
    channel: "Instagram",
    status: "Programado",
    publishDate: "Lun 6",
    notes: "Grabar en local, luz natural",
  },
  {
    id: "c2",
    product: "Combo parrillero",
    format: "Carrusel",
    channel: "Instagram",
    status: "Programado",
    publishDate: "Mié 8",
    notes: "3 slides + precio",
  },
  {
    id: "c3",
    product: "Quesos artesanales",
    format: "Historia",
    channel: "Instagram",
    status: "En revisión",
    publishDate: "Jue 9",
    notes: "Falta aprobación de precio",
  },
  {
    id: "c4",
    product: "Vinos de la semana",
    format: "Post",
    channel: "Facebook",
    status: "En pausa",
    publishDate: "Sin fecha",
    notes: "Esperando stock",
  },
  {
    id: "c5",
    product: "Promo fin de semana",
    format: "Reel",
    channel: "TikTok",
    status: "Listo",
    publishDate: "Vie 10",
    notes: "Editado y aprobado",
  },
  {
    id: "c6",
    product: "Fiambres importados",
    format: "Carrusel",
    channel: "Instagram",
    status: "Listo",
    publishDate: "Sáb 11",
    notes: "Programado en Meta",
  },
]

export const libraryItems: LibraryItem[] = [
  {
    id: "cp1",
    kind: "copy",
    title: "Headline home Diego Aranda",
    projectId: "diego-aranda-web",
    preview: "Diseño y desarrollo web que convierte visitas en clientes.",
    status: "Aprobado",
    date: "2 jul",
    tags: ["home", "hero"],
  },
  {
    id: "cp2",
    kind: "copy",
    title: "Caption combo parrillero",
    projectId: "rey-abasto-marketing",
    preview: "El finde se arma acá. Combo parrillero con todo lo que necesitás...",
    status: "Publicado",
    date: "1 jul",
    tags: ["instagram", "promo"],
  },
  {
    id: "cp3",
    kind: "copy",
    title: "Descripción catálogo Medalleros",
    projectId: "medalleros-web",
    preview: "Medallas y trofeos personalizados para cada logro.",
    status: "Borrador",
    date: "30 jun",
    tags: ["catálogo", "seo"],
  },
  {
    id: "cp4",
    kind: "copy",
    title: "Email bienvenida newsletter",
    projectId: "rey-abasto-marketing",
    preview: "Gracias por sumarte. Cada semana te contamos las mejores ofertas...",
    status: "Aprobado",
    date: "28 jun",
    tags: ["email", "newsletter"],
  },
  {
    id: "as1",
    kind: "asset",
    title: "hero-diego-aranda.jpg",
    name: "hero-diego-aranda.jpg",
    projectId: "diego-aranda-web",
    type: "Imagen",
    date: "2 jul",
    tags: ["hero", "web"],
  },
  {
    id: "as2",
    kind: "asset",
    title: "brief-medalleros.pdf",
    name: "brief-medalleros.pdf",
    projectId: "medalleros-web",
    type: "PDF",
    date: "1 jul",
    tags: ["brief", "cliente"],
  },
  {
    id: "as3",
    kind: "asset",
    title: "mockup-landing-v2.fig",
    name: "mockup-landing-v2.fig",
    projectId: "diego-aranda-web",
    type: "Mockup",
    date: "30 jun",
    tags: ["figma", "landing"],
  },
  {
    id: "as4",
    kind: "asset",
    title: "ref-competencia-abasto.png",
    name: "ref-competencia-abasto.png",
    projectId: "rey-abasto-marketing",
    type: "Referencia",
    date: "29 jun",
    tags: ["inspiración"],
  },
  {
    id: "as5",
    kind: "asset",
    title: "combo-parrillero.jpg",
    name: "combo-parrillero.jpg",
    projectId: "rey-abasto-marketing",
    type: "Imagen",
    date: "28 jun",
    tags: ["producto", "instagram"],
  },
  {
    id: "ll1",
    kind: "link",
    title: "Paleta de colores marca",
    projectId: "diego-aranda-web",
    category: "Diseño",
    url: "https://coolors.co/palette",
    note: "Colores definitivos aprobados por el cliente.",
    date: "2 jul",
    tags: ["diseño"],
  },
  {
    id: "ll2",
    kind: "link",
    title: "Guía de tono Rey del Abasto",
    projectId: "rey-abasto-marketing",
    category: "Contenido",
    url: "https://drive.google.com/tono",
    note: "Cercano, directo y con humor porteño.",
    date: "1 jul",
    tags: ["tono"],
  },
  {
    id: "ll3",
    kind: "link",
    title: "Banco de imágenes producto",
    projectId: "rey-abasto-marketing",
    category: "Assets",
    url: "https://drive.google.com/fotos",
    note: "Fotos actualizadas de productos.",
    date: "30 jun",
    tags: ["assets"],
  },
  {
    id: "ll4",
    kind: "link",
    title: "Documentación API catálogo",
    projectId: "medalleros-web",
    category: "Desarrollo",
    url: "https://docs.medalleros.dev",
    note: "Endpoints para integrar el catálogo.",
    date: "29 jun",
    tags: ["dev"],
  },
  {
    id: "nt1",
    kind: "note",
    title: "Proceso de publicación semanal",
    projectId: "rey-abasto-marketing",
    preview: "1) Cerrar calendario lunes. 2) Grabar martes. 3) Editar miércoles...",
    date: "2 jul",
    tags: ["proceso", "workflow"],
  },
  {
    id: "nt2",
    kind: "note",
    title: "Checklist de deploy",
    projectId: "diego-aranda-web",
    preview: "Revisar meta tags, imágenes optimizadas, formularios y analytics.",
    date: "1 jul",
    tags: ["deploy", "checklist"],
  },
  {
    id: "nt3",
    kind: "note",
    title: "Ideas de contenido pendientes",
    projectId: "rey-abasto-marketing",
    preview: "Reel detrás de escena, testimonios de clientes, tips de conservación.",
    date: "29 jun",
    tags: ["ideas"],
  },
]

export const accessReferences: AccessReference[] = [
  {
    id: "ar1",
    platform: "ClickUp",
    account: "diego@go-os.app",
    loginUrl: "https://app.clickup.com",
    note: "Workspace principal de operaciones.",
    storedIn: "1Password",
  },
  {
    id: "ar2",
    platform: "Vercel",
    account: "diego@go-os.app",
    loginUrl: "https://vercel.com/login",
    note: "Deploys de todos los proyectos web.",
    storedIn: "Apple Passwords",
  },
  {
    id: "ar3",
    platform: "Meta Business",
    account: "reydelabasto",
    loginUrl: "https://business.facebook.com",
    note: "Publicación y anuncios de Rey del Abasto.",
    storedIn: "Bitwarden",
  },
]

export const quickLinks = [
  { label: "ClickUp", href: "#" },
  { label: "Figma", href: "#" },
  { label: "Vercel", href: "#" },
  { label: "Drive", href: "#" },
  { label: "Notion", href: "#" },
  { label: "WhatsApp", href: "#" },
]

export const libraryCopies = libraryItems.filter((item) => item.kind === "copy")
export const libraryAssets = libraryItems.filter((item) => item.kind === "asset")
export const libraryLinks = libraryItems.filter((item) => item.kind === "link")
export const libraryNotes = libraryItems.filter((item) => item.kind === "note")
